application: givabit-dev
version: 3
runtime: python27
threadsafe: no
api_version: 1

handlers:
#- url: /static
#  static_dir: static

- url: /.*
  script: givabit/webapp/webapp.py
  secure: always
  login: admin # Dev config

builtins:
# For test
- remote_api: on
