application: givabit-dev
version: 4
runtime: python27
threadsafe: no
api_version: 1

handlers:
#- url: /static
#  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: givabit/webapp/webapp.py
  secure: always
  #login: admin # Dev config

builtins:
# For test
- remote_api: on
