application: givabit-dev
version: 2
runtime: python27
threadsafe: no
api_version: 1

handlers:
#- url: /static
#  static_dir: static

- url: /.*
  script: givabit/webapp/webapp.py

builtins:
# For test
- remote_api: on
